# Generated by Django 5.1.4 on 2025-05-23 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform_type', models.CharField(max_length=50)),
                ('is_connected', models.BooleanField(default=True)),
                ('twilio_account_sid', models.CharField(max_length=100)),
                ('twilio_auth_token', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteChatConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform_type', models.CharField(max_length=50)),
                ('is_connected', models.BooleanField(default=True)),
                ('iframe_token', models.CharField(max_length=100)),
                ('theme', models.CharField(default='dark', max_length=50)),
                ('allowed_domains', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_type', models.CharField(choices=[('website_chat', 'Website Chat'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('messenger', 'Messenger'), ('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('voice', 'Voice')], max_length=50)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
