# Generated by Django 5.1.4 on 2025-05-28 12:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_connections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.UUIDField()),
                ('platform_type', models.CharField(max_length=50)),
                ('user_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
