# Generated by Django 5.1.4 on 2025-05-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_connections', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitechatconnection',
            name='session_tracking',
            field=models.JSONField(default=dict),
        ),
    ]
