# Generated by Django 5.1.4 on 2025-05-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_connections', '0004_websitechatconnection_session_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='handling_mode',
            field=models.CharField(choices=[('ai', 'AI'), ('human', 'Human')], default='ai', max_length=10),
        ),
    ]
