# Generated by Django 5.1.4 on 2025-06-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_connections', '0005_chatsession_handling_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitechatconnection',
            name='custom_icon',
            field=models.ImageField(blank=True, null=True, upload_to='chat_widget_icons/'),
        ),
    ]
