version: '3'

services:
  web:
    build: .
    image: us-central1-docker.pkg.dev/esaasolution/csa247-repo/csa247:${IMAGE_TAG:-latest}
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn 247csa.wsgi:application --bind 0.0.0.0:8000 --workers 3"

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=csa247
      - MYSQL_USER=csa247user
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  mysql_data:
  static_volume:
  media_volume: 