version: '3.8'

services:
  web:
    build: .
    command: gunicorn 247csa.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8000
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: 