# Generated by Django 5.1.4 on 2025-06-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='default_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', help_text='Default role for new team members', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, help_text="A brief description of your team's purpose"),
        ),
        migrations.AddField(
            model_name='team',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', help_text='Public teams can be discovered by other users', max_length=20),
        ),
    ]
