# Generated by Django 5.1.4 on 2025-01-17 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_utility', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useremailconfiguration',
            options={'ordering': ['-is_primary', '-created_at'], 'verbose_name': 'Email Configuration', 'verbose_name_plural': 'Email Configurations'},
        ),
        migrations.AddField(
            model_name='useremailconfiguration',
            name='is_primary',
            field=models.BooleanField(default=False, help_text="Whether this is the user's primary email configuration"),
        ),
        migrations.AlterField(
            model_name='useremailconfiguration',
            name='credentials',
            field=models.JSONField(help_text='Encrypted credentials and provider-specific settings'),
        ),
        migrations.AlterField(
            model_name='useremailconfiguration',
            name='email',
            field=models.EmailField(help_text='Email address for this configuration', max_length=254),
        ),
        migrations.AlterField(
            model_name='useremailconfiguration',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this email configuration is currently active'),
        ),
        migrations.AlterField(
            model_name='useremailconfiguration',
            name='provider_type',
            field=models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook'), ('yahoo', 'Yahoo Mail'), ('other', 'Other IMAP Provider')], help_text='Type of email provider', max_length=50),
        ),
        migrations.AlterField(
            model_name='useremailconfiguration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_configurations', to=settings.AUTH_USER_MODEL),
        ),
    ]
