# Generated by Django 5.1.4 on 2025-01-19 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0009_alter_message_eml'),
        ('email_utility', '0002_alter_useremailconfiguration_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sync', models.DateTimeField(blank=True, help_text='Last time the mailbox was synced', null=True)),
                ('sync_enabled', models.BooleanField(default=True, help_text='Whether automatic syncing is enabled')),
                ('custom_folders', models.JSONField(blank=True, default=dict, help_text='Custom folder mapping and configuration')),
                ('email_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_config', to='email_utility.useremailconfiguration')),
                ('mailbox', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_config', to='django_mailbox.mailbox')),
            ],
            options={
                'verbose_name': 'Mailbox Configuration',
                'verbose_name_plural': 'Mailbox Configurations',
            },
        ),
    ]
