# Generated by Django 5.1.4 on 2025-01-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_utility', '0003_mailboxconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremailconfiguration',
            name='encrypted_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
