# Generated by Django 5.1.5 on 2025-01-25 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_utility', '0004_useremailconfiguration_encrypted_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentEmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=100)),
                ('task_type', models.CharField(choices=[('auto_respond', 'Automatic Response'), ('draft_email', 'Draft Email'), ('reply_to_email', 'Reply to Email'), ('forward_email', 'Forward Email')], help_text='The type of email task this agent will perform', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_configs', to='email_utility.useremailconfiguration')),
            ],
            options={
                'unique_together': {('email_config', 'agent_id')},
            },
        ),
    ]
