# Generated by Django 5.1.5 on 2025-01-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_utility', '0005_agentemailconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailFunctionSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('auto_respond', 'Automatic Response'), ('save_email', 'Save Email'), ('reply_to_email', 'Reply to Email'), ('forward_email', 'Forward Email')], help_text='The type of email task this schema is for', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('parameters', models.JSONField(help_text='JSON schema for function parameters')),
                ('instructions', models.TextField(help_text='Instructions for the AI on how to use this function')),
                ('handler_path', models.CharField(help_text="Python path to the function handler (e.g., 'email_utility.handlers.save_email')", max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Function Schema',
                'verbose_name_plural': 'Email Function Schemas',
            },
        ),
        migrations.AlterField(
            model_name='agentemailconfiguration',
            name='task_type',
            field=models.CharField(choices=[('auto_respond', 'Automatic Response'), ('save_email', 'Save Email'), ('reply_to_email', 'Reply to Email'), ('forward_email', 'Forward Email')], help_text='The type of email task this agent will perform', max_length=50),
        ),
    ]
