# Generated by Django 5.1.5 on 2025-01-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_utility', '0006_emailfunctionschema_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentemailconfiguration',
            name='task_type',
        ),
        migrations.AddField(
            model_name='agentemailconfiguration',
            name='task_types',
            field=models.JSONField(default=list, help_text='List of email tasks this agent will perform'),
        ),
    ]
