# Generated by Django 5.1.4 on 2025-06-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_utility', '0007_remove_agentemailconfiguration_task_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agentemailconfiguration',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='agentemailconfiguration',
            name='email_config',
        ),
        migrations.DeleteModel(
            name='EmailFunctionSchema',
        ),
        migrations.DeleteModel(
            name='AgentEmailConfiguration',
        ),
    ]
