# Generated by Django 5.1.4 on 2025-06-02 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('question', models.TextField(verbose_name='Main Question')),
                ('response_type', models.CharField(choices=[('answer', 'Direct Answer'), ('subquestions', 'Sub-questions')], default='answer', max_length=20, verbose_name='Response Type')),
                ('answer', models.TextField(blank=True, verbose_name='Answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQSubQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Sub-question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='faq_management.faq')),
            ],
            options={
                'verbose_name': 'FAQ Sub-question',
                'verbose_name_plural': 'FAQ Sub-questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['content_type', 'object_id'], name='faq_managem_content_3792a1_idx'),
        ),
    ]
