# Generated by Django 5.1.4 on 2025-06-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='faq',
            name='faq_managem_content_3792a1_idx',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='object_id',
        ),
        migrations.AddField(
            model_name='faq',
            name='faqid',
            field=models.CharField(db_index=True, default='', max_length=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='response_type',
            field=models.CharField(choices=[('answer', 'Direct Answer'), ('subquestions', 'Sub-questions')], default='answer', max_length=20),
        ),
        migrations.AlterField(
            model_name='faqsubquestion',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faqsubquestion',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faqsubquestion',
            name='question',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['faqid'], name='faq_managem_faqid_fb533e_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['is_active'], name='faq_managem_is_acti_06645c_idx'),
        ),
    ]
