# Generated by Django 5.1.4 on 2025-01-05 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='snippet',
            new_name='body',
        ),
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='email',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.userprofile'),
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('recipients', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_replied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(max_length=255)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('media_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
