# Generated by Django 5.1.4 on 2025-06-06 15:46

from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
    Customer = apps.get_model('mycrm', 'Customer')
    for customer in Customer.objects.all():
        customer.task_uuid = uuid.uuid4()
        customer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mycrm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='task_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(gen_uuid),
        migrations.AlterField(
            model_name='customer',
            name='task_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
