# Generated by Django 5.1.4 on 2025-06-06 16:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrm', '0002_add_customer_task_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='activity_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
