# Generated by Django 5.1.4 on 2025-06-06 16:28

from django.db import migrations
import uuid

def gen_activity_uuid(apps, schema_editor):
    Customer = apps.get_model('mycrm', 'Customer')
    for customer in Customer.objects.all():
        customer.activity_uuid = uuid.uuid4()
        customer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mycrm', '0003_customer_activity_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_activity_uuid),
    ]
