# Generated by Django 5.1.4 on 2025-06-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrm', '0006_customer_customer_number_alter_customer_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(editable=False, max_length=25, null=True, unique=True),
        ),
    ]
