# Generated by Django 5.1.4 on 2025-06-13 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrm', '0007_alter_customer_customer_number'),
        ('team', '0002_team_default_role_team_description_team_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='teams',
            field=models.ManyToManyField(related_name='customers', to='team.team'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='teams',
            field=models.ManyToManyField(related_name='interactions', to='team.team'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='teams',
            field=models.ManyToManyField(related_name='tasks', to='team.team'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='created_customers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interaction',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='created_interactions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
