# Generated by Django 5.1.4 on 2025-06-11 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticketcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Ticket categories'},
        ),
        migrations.RemoveField(
            model_name='ticketcategory',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image to help describe the issue', null=True, upload_to='ticket_images/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticketcategory'),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
