# Generated by Django 5.1.4 on 2025-06-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_default_role_team_description_team_visibility'),
        ('tickets', '0003_alter_ticketcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='teams',
            field=models.ManyToManyField(related_name='%(class)ss', to='team.team'),
        ),
    ]
