# Generated by Django 5.1.4 on 2025-05-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csa', '0002_csa_firebase_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csa',
            name='firebase_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
