# Generated by Django 5.1.4 on 2025-05-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csa', '0004_csa_knowledge_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='csa',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('ready', 'Ready')], default='draft', max_length=20),
        ),
    ]
