# Generated by Django 5.1.4 on 2025-05-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csa', '0005_csa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='csa',
            name='default_handling_mode',
            field=models.CharField(choices=[('ai', 'AI'), ('human', 'Human')], default='ai', max_length=10),
        ),
    ]
