# Generated by Django 5.1.4 on 2025-06-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csa', '0006_csa_default_handling_mode'),
        ('team', '0002_team_default_role_team_description_team_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='csa',
            name='teams',
            field=models.ManyToManyField(related_name='csas', to='team.team'),
        ),
    ]
